schedules:
- cron: "44 18 * * 1-5"
  displayName: Evening Schedule (Mon-Fri) - Main Branch
  branches:
    include:
      - scheduler
  always: true
  variables:
    vmName: "syncfusion"

- cron: "0 22 * * 1-5"
  displayName: Night Schedule (Mon-Fri) - Main Branch
  branches:
    include:
      - scheduler
  always: true
  variables:
    vmName: "syncfusion"

pool:
  vmImage: 'ubuntu-latest'

jobs:
 - template: morning_schedule.yml
   parameters:
     vmName: $(vmName)

 - template: night_schedule.yml
   parameters:
     vmName: $(vmName)

 - script: echo "This is a scheduled build at 6:43 PM and 10:00 PM from Monday to Friday."
   displayName: 'Scheduled Task'

