# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  branches:
    include:
      - development
      - hotfix/boldbi*
      - release/boldbi*

pool:
  vmImage: ubuntu-latest

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo 'Build_SourceBranchName'
        echo $(Build.SourceBranchName)
        echo '$Build_SourceBranch'
        echo $(Build.SourceBranch)
    displayName: 'Branch'  
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        cd embed-sdk/boldbi-sdk
        npm install
        npm install -g typescript
        tsc -v
        tsc
        npm run build-webpack
    displayName: 'NPM Build' 
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo "$(pwd)"
        echo "$(date)"
        datetime=$(date +"%d%m%Y%H%M%S")
        echo "Date and time = $datetime"
        echo "##vso[task.setvariable variable=datetime]$datetime"
        ls
    displayName: 'Date and Time' 

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/development') }}:
    - task: AWSCLI@1
      inputs:
        awsCredentials: 'Aws access'
        regionName: 'us-east-1'
        awsCommand: 's3'
        awsSubCommand: 'cp'
        awsArguments: >
          /home/vsts/work/1/s/webpack/dist/boldbi-embed.js
          s3://cdn.boldbi.com/embedded-sdk/dev/$(datetime)/
          --acl public-read
      displayName: 'AWS S3 bucket' 
  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/release/boldbi') }}:
    - task: AWSCLI@1
      inputs:
        awsCredentials: 'Aws access'
        regionName: 'us-east-1'
        awsCommand: 's3'
        awsSubCommand: 'cp'
        awsArguments: >
          /home/vsts/work/1/s/webpack/dist/boldbi-embed.js
          s3://cdn.boldbi.com/embedded-sdk/release/$(datetime)/
          --acl public-read
      displayName: 'AWS S3 bucket' 

  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/boldbi') }}:
    - task: AWSCLI@1
      inputs:
        awsCredentials: 'Aws access'
        regionName: 'us-east-1'
        awsCommand: 's3'
        awsSubCommand: 'cp'
        awsArguments: >
          /home/vsts/work/1/s/webpack/dist/boldbi-embed.js
          s3://cdn.boldbi.com/embedded-sdk/hotfix/$(datetime)/
          --acl public-read
      displayName: 'AWS S3 bucket' 

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        if [[ "${BUILD_SOURCEBRANCH}" == "refs/heads/release/boldbi"* ]]; then
          echo "https://cdn.boldbi.com/embedded-sdk/release/$(datetime)/boldbi-embed.js"
        elif [[ "${BUILD_SOURCEBRANCH}" == "refs/heads/development" ]]; then
          echo "https://cdn.boldbi.com/embedded-sdk/dev/$(datetime)/boldbi-embed.js"
        elif [[ "${BUILD_SOURCEBRANCH}" == "refs/heads/hotfix/boldbi"* ]]; then
          echo "https://cdn.boldbi.com/embedded-sdk/hotfix/$(datetime)/boldbi-embed.js"
        else
          echo "CDN Link not generated"
        fi
    displayName: 'CDN publish Link'  
        
  