trigger:
  - none

schedules:
- cron: '38 17 * * 1-5'
  displayName: Test1
  always: true
  branches:
    include:
    - scheduler

- cron: '40 17 * * 1-5'
  displayName: Test2
  always: true
  branches:
    include:
    - scheduler

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world Test1'
  condition: eq(variables['Build.CronSchedule.DisplayName'], 'Test1') 

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world Test2'
  condition: eq(variables['Build.CronSchedule.DisplayName'], 'Test2') 

  
- task: AzureCLI@2
  inputs:
    azureSubscription: 'SF3362-BoldBI-DevOps-SivanesanSaravanan(bbceebb1-216e-46f8-82c1-500bdea55db4)'
    scriptType: 'batch'
    scriptLocation: 'scriptPath'
    scriptPath: 'az vm start --resource-group server-docker --name server'
  condition: eq(variables['Build.CronSchedule.DisplayName'], 'Test1')

- task: AzureCLI@2
  inputs:
    azureSubscription: 'SF3362-BoldBI-DevOps-SivanesanSaravanan(bbceebb1-216e-46f8-82c1-500bdea55db4)'
    scriptType: 'batch'
    scriptLocation: 'scriptPath'
    scriptPath: 'az vm stop --resource-group server-docker --name server'
  condition: eq(variables['Build.CronSchedule.DisplayName'], 'Test2')