# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
    - none

pool:
  vmImage: ubuntu-latest
  
parameters:
  - name: package_link
    displayName: Azure Package URL
    type: string
  - name: repository
    displayName: Repository-URL
    type: string
  - name: branch
    displayName: Branch
    type: string