# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  - none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: package_link
    displayName: Azure Package URL
    type: string
    values:
      - http://files2.syncfusion.com/Installs/BoldBI/23-11-2022/BoldBIEnterpriseEdition_AzurePackage_5.3.53_11232022_091427.zip

  - name: repository
    displayName: Repository-URL
    type: string

  - name: branch
    displayName: Branch
    type: string
    values:
      - testing
      
  - name: git_user_email
    displayName: Git User Email
    type: string

  - name: git_user_name
    displayName: Git User Name
    type: string
steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo "$(pwd)"
        wget --no-check-certificate '${{parameters.package_link}}'
        unzip Bold*
        ls

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Check if the branch exists
        echo "$(pwd)"
        if git ls-remote --heads '${{parameters.repository}}' '${{parameters.branch}}' | grep -q '${{parameters.branch}}'; then
          # If the branch exists, clone the repository and switch to the branch
          git clone -b '${{parameters.branch}}' '${{parameters.repository}}' azure-boldbi
          cd azure-boldbi
          echo "$(pwd)"
        else
          # If the branch doesn't exist, create it, clone the repository and switch to the branch
          git clone '${{parameters.repository}}' azure-boldbi
          cd azure-boldbi
          git checkout -b '${{parameters.branch}}'
        fi

        # Copy the files and folders to the cloned location
        #cp git.sh $folder
        echo "$(pwd)"
        cp -r /home/vsts/work/1/s/Bold*/* /home/vsts/work/1/s/azure-boldbi
        echo "$(pwd)"
        git config user.email "${{parameters.git_user_email}}"
        git config user.name "${{parameters.git_user_name}}"

        # Commit and push the changes
        git add .
        git commit -m "Latest packages update"
        git push origin '${{parameters.branch}}'
        ls
