trigger:
  - none

schedules:
- cron: '27 17 * * 1-5'
  displayName: Test1
  always: true
  branches:
    include:
    - scheduler

- cron: '29 17 * * 1-5'
  displayName: Test2
  always: true
  branches:
    include:
    - scheduler

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world Test1'
  condition: eq(variables['Build.CronSchedule.DisplayName'], 'Test1') 

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world Test2'
  condition: eq(variables['Build.CronSchedule.DisplayName'], 'Test2') 
  