# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  - none

pool:
  vmImage: ubuntu-latest

parameters:
  - name:  command
    displayName: Command
    type: string
    values:
      - False
      - True
  - name: git_link
    displayName: GitHub
    type: string

   
  - name:  azure_deployment_upgrade
    displayName: Azure APP Service upgrade
    type: string
    values:
      - False
      - True

variables:
- name: Command_shell
  value: ${{parameters.command}}

- name: AzureUpgrade
  value: ${{parameters.azure_deployment_upgrade}}

steps:
  - ${{ if eq(variables.Command_shell, True) }}:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo 'Hello world'
          ls
          echo "Hi sivanesan"
  - ${{ else }}:
      - script: echo "It is commit not triggered"
  - ${{ if eq(variables.AzureUpgrade, True) }}:
    - task: AzureAppServiceManage@0
      inputs:
        azureSubscription: 'SF3362-BoldBI-DevOps-SivanesanSaravanan(bbceebb1-216e-46f8-82c1-500bdea55db4)'
        Action: 'Stop Azure App Service'
        WebAppName: 'azure-siva-arm'
  - ${{ else }}:
      - script: echo "Service not trigerred"