trigger:
  - none

schedules:
- cron: '24 7 * * 1-5'
  displayName: Task1
  always: true
  branches:
    include:
    - scheduler

- cron: '10 18 * * 1-5'
  displayName: Task2
  always: true
  branches:
    include:
    - scheduler

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'hotfix'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az vm start --resource-group boldbiteamlab-boldbi-on-premise-238719 --name syncfusion'
  condition: eq(variables['Build.CronSchedule.DisplayName'], 'Task1')

- task: AzureCLI@2
  inputs:
    azureSubscription: 'hotfix'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az vm start --resource-group server-docker --name server'
  condition: eq(variables['Build.CronSchedule.DisplayName'], 'Test2')

- task: AzureCLI@2
  inputs:
    azureSubscription: 'hotfix'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az appservice plan update --name BoldBIAppSvcPlan --resource-group boldbiteamlab-BoldBI-On-Premise-238719 --sku P1V3'
 # condition: eq(variables['Build.CronSchedule.DisplayName'], 'Test2')
  
