# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  branches:
    include:
      - development
      - hotfix/boldbi*
      - release/boldbi*

pool:
  vmImage: ubuntu-latest

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo 'Build_SourceBranchName'
        echo $(Build.SourceBranchName)
        echo '$Build_SourceBranch'
        echo $(Build.SourceBranch)
    displayName: 'Branch'  
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        cd embed-sdk/boldbi-sdk
        npm install
        npm install -g typescript
        tsc -v
        tsc
        npm run build-webpack
        export studio_version=$(STUDIO_VERSION)
        export revisionnumber=$(REVISIONNUMBER)
        gulp update-version
        sed -i 's/#registry#/$(REGISTRY)/g' .npmrc
        sed -i 's/#username#/$(USERNAME)/g' .npmrc
        sed -i 'sed -i 's/#password#/$(PASSWORD)/g' .npmrc
        cat .npmrc
        pwd
    displayName: 'Build and Deploy'

  




      
