# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  - none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: package_link
    displayName: Azure Package URL
    type: string
    values:
      - http://files2.syncfusion.com/Installs/BoldBI/08-04-2023/BoldBIEnterpriseEdition_AzurePackage_6.2.7_04082023_043215.zip

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'SF3362-BoldBI-DevOps-SivanesanSaravanan(bbceebb1-216e-46f8-82c1-500bdea55db4)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az webapp stop --name azure-siva-arm --resource-group sivanew'