# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  - none

pool:
  vmImage: ubuntu-latest

parameters:
    
  - name:  azure_deployment_upgrade
    displayName: Azure APP Service upgrade
    type: string
    values:
      - False
      - True

variables:
- name: AzureUpgrade
  value: ${{parameters.azure_deployment_upgrade}}

steps:
  - ${{ if eq(variables.AzureUpgrade, True) }}:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'SF3362-BoldBI-DevOps-SivanesanSaravanan(bbceebb1-216e-46f8-82c1-500bdea55db4)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # stop the azure app service
            az webapp stop --name azure-siva-arm --resource-group sivanew
            sleep 60
          # Remove the external repository details in Deployment center
            az webapp deployment source delete --name azure-siva-arm --resource-group sivanew
            sleep 60
          #  Add the repo details in Deployment center 
            az webapp deployment source config --name azure-siva-arm --resource-group sivanew --repo-url https://github.com/boldbi/azure-arm-template.git --branch v6.2.7 --manual-integration   
          
    - task: AzureAppServiceManage@0
      inputs:
        azureSubscription: 'SF3362-BoldBI-DevOps-SivanesanSaravanan(bbceebb1-216e-46f8-82c1-500bdea55db4)'
        Action: 'Start Azure App Service'
        WebAppName: 'azure-siva-arm'